<?php

namespace AppBundle\Repository;

/**
 * Clim_chauffageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Clim_chauffageRepository extends \Doctrine\ORM\EntityRepository
{
}
