<?php

namespace AppBundle\Repository;

/**
 * LumiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LumiereRepository extends \Doctrine\ORM\EntityRepository
{
}
