<?php

namespace AppBundle\Repository;

/**
 * Mode_clim_chauffageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mode_clim_chauffageRepository extends \Doctrine\ORM\EntityRepository
{
}
