<?php

namespace AppBundle\Repository;

/**
 * VoletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoletRepository extends \Doctrine\ORM\EntityRepository
{
}
