<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPj1dg60\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPj1dg60/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPj1dg60.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPj1dg60\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerPj1dg60\appTestDebugProjectContainer([
    'container.build_hash' => 'Pj1dg60',
    'container.build_id' => 'cf851745',
    'container.build_time' => 1578490984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPj1dg60');
