<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\DomoHomeController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.bhcofmc']) ? $this->services['service_locator.bhcofmc'] : $this->load('getServiceLocator_BhcofmcService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController:createModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController:deleteModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController:editModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController:listeModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController:createScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController:deleteScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController:editScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController:listeScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DomoHomeController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.bhcofmc']) ? $this->services['service_locator.bhcofmc'] : $this->load('getServiceLocator_BhcofmcService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController::createModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController::deleteModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController::editModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ModeChauffageController::listeModeAction' => function () {
    return ${($_ = isset($this->services['service_locator.hk_4pyi']) ? $this->services['service_locator.hk_4pyi'] : $this->load('getServiceLocator_Hk4pyiService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController::createScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController::deleteScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController::editScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ScenarioController::listeScenarioAction' => function () {
    return ${($_ = isset($this->services['service_locator.bkzzca5']) ? $this->services['service_locator.bkzzca5'] : $this->load('getServiceLocator_Bkzzca5Service.php')) && false ?: '_'};
}]));
