<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6v5jazk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6v5jazk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6v5jazk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6v5jazk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6v5jazk\appDevDebugProjectContainer([
    'container.build_hash' => '6v5jazk',
    'container.build_id' => '5fa5b350',
    'container.build_time' => 1582200858,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6v5jazk');
