<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mode_clim_chauffage extends \AppBundle\Entity\Mode_clim_chauffage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'temp_max', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'temp_min', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'clim_chauffages', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'scenarios'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'temp_max', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'temp_min', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'clim_chauffages', '' . "\0" . 'AppBundle\\Entity\\Mode_clim_chauffage' . "\0" . 'scenarios'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mode_clim_chauffage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempMax($tempMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempMax', [$tempMax]);

        return parent::setTempMax($tempMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempMax', []);

        return parent::getTempMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempMin($tempMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempMin', [$tempMin]);

        return parent::setTempMin($tempMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempMin', []);

        return parent::getTempMin();
    }

    /**
     * {@inheritDoc}
     */
    public function addClimChauffage(\AppBundle\Entity\Clim_chauffage $climChauffage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClimChauffage', [$climChauffage]);

        return parent::addClimChauffage($climChauffage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClimChauffage(\AppBundle\Entity\Clim_chauffage $climChauffage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClimChauffage', [$climChauffage]);

        return parent::removeClimChauffage($climChauffage);
    }

    /**
     * {@inheritDoc}
     */
    public function getClimChauffages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClimChauffages', []);

        return parent::getClimChauffages();
    }

    /**
     * {@inheritDoc}
     */
    public function addScenario(\AppBundle\Entity\Scenario $scenario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScenario', [$scenario]);

        return parent::addScenario($scenario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScenario(\AppBundle\Entity\Scenario $scenario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScenario', [$scenario]);

        return parent::removeScenario($scenario);
    }

    /**
     * {@inheritDoc}
     */
    public function getScenarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScenarios', []);

        return parent::getScenarios();
    }

}
